{{ config(materialized='view') }}

SELECT
    CUSTOMER_HK,
    CUSTOMER_HASHDIFF,
    CAST(NULL AS STRING) AS CUSTOMER_ADDRESS_HASHDIFF,
    'SAT_CUSTOMER_DETAILS' AS SATELLITE_NAME_1,
    CAST(NULL AS STRING) AS SATELLITE_NAME_2,
    LOAD_DATETIME,
    SOURCE
FROM {{ ref('stg_customers') }}
