{{ config(materialized='view') }}

SELECT
    CUSTOMER_HK,
    CAST(NULL AS STRING) AS CUSTOMER_HASHDIFF,
    CUSTOMER_ADDRESS_HASHDIFF,
    CAST(NULL AS STRING) AS SATELLITE_NAME_1,
    'SAT_CUSTOMER_ADDRESS' AS SATELLITE_NAME_2,
    LOAD_DATETIME,
    SOURCE
FROM {{ ref('stg_customer_addresses') }}
